sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3.5-5.7"
env:
  - DJANGO="Django~=1.10"
  - DJANGO="Django~=1.11"

install:
  - pip install -q $DJANGO
script:
  - python runtests.py
